services:
  air:
    image: cosmtrek/air:v1.62.0
    working_dir: /app
    volumes:
      - ./:/app
      - ./test/uploads:/var/www/owo/uploads
      - ./web/static:/var/www/owo/static
      - ./web/templates:/var/www/owo/templates
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - TZ=Europe/Moscow
    command: air -c .air.toml

  # owo:
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile
  #   volumes:
  #     - /media/ubuntu-operator/7fff58c3-3e1f-4c91-8ef4-0aabb30c27f1/Documents/backups/owwo:/var/www/owwo/shared
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - PORT=8080
  #     - TZ=Europe/Moscow
