services:
  owo:
    image: owo:latest
    volumes:
      - ./owo/uploads:/var/www/owo/uploads

      - ./owo/authorized_keys:/root/.ssh/authorized_keys
      - ./owo/ssh_keys/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key
      - ./owo/ssh_keys/ssh_host_rsa_key.pub:/etc/ssh/ssh_host_rsa_key.pub
    ports:
      - "8080:8080"
      - "2222:22"
    environment:
      - PORT=8080
      - TZ=Europe/Moscow
